server:
  port: 8080
  servlet:
    context-path: /demo-rest-infrastructure-dev/v1/

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: admin
    password: admin1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

########## Config Spring Doc Open Api ##########
springdoc:
  info:
    enabled-server-https: false
########## End Config Spring Doc Open Api ##########

########## Config Actuator ##########
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,metrics,info,caches
  health:
    show-details: always
    circuitbreakers:
      enabled: false
    ratelimiters:
      enabled: false
    elasticsearch:
      enabled: false
  info:
    env:
      enabled: true
########## End Config Actuator ##########
